/// DO NOT EDIT!
/// Autogenerated CLIENT code for lan866x.proto
/// Generated by Microchip SOME/IP generator
/// Generator version: 0.1.10
/// Template version: 0.7.0
///

// DOM-IGNORE-BEGIN
/*
Copyright (C) 2025, Microchip Technology Inc., and its subsidiaries. All rights reserved.

The software and documentation is provided by microchip and its contributors
"as is" and any express, implied or statutory warranties, including, but not
limited to, the implied warranties of merchantability, fitness for a particular
purpose and non-infringement of third party intellectual property rights are
disclaimed to the fullest extent permitted by law. In no event shall microchip
or its contributors be liable for any direct, indirect, incidental, special,
exemplary, or consequential damages (including, but not limited to, procurement
of substitute goods or services; loss of use, data, or profits; or business
interruption) however caused and on any theory of liability, whether in contract,
strict liability, or tort (including negligence or otherwise) arising in any way
out of the use of the software and documentation, even if advised of the
possibility of such damage.

Except as expressly permitted hereunder and subject to the applicable license terms
for any third-party software incorporated in the software and any applicable open
source software license terms, no license or other rights, whether express or
implied, are granted under any patent or other intellectual property rights of
Microchip or any third party.
*/
// DOM-IGNORE-END

#pragma once

#ifdef WIN32
#include <windows.h>
#else
#include <pthread.h>
#include <sched.h>
#endif

#include <stdint.h>
#include <stdbool.h>
#include <thread>
#include <queue>
#include <vector>
#include <mutex>
#include <optional>
#include <condition_variable>
#include "someip.h"
#include "lan866x_client.hpp"

using namespace std;

namespace microchip {
namespace rcp {

// *****************************************************************************
// *****************************************************************************
// Section: Public and hidden API
// *****************************************************************************
// *****************************************************************************

class LAN866XClientImpl;

class ep_wait_vars
{
  public:
    uint8_t rxBuf[1500];
    SOME_IP_SEM_t semWaitForAck;
    enum SOMEIP_ReturnCode retCode;
    uint16_t rxLen;
    bool success;
};

class FunctionEnvironment
{
  public:
    FunctionEnvironment(LAN866XClientImpl *pClient, SOMETR_t *pTransmit, bool fireAndForget);
    ~FunctionEnvironment();

    static bool IsValid(FunctionEnvironment *pCheck);

    ep_wait_vars *GetWait()
    {
        return &m_wait;
    }

    struct SOMEIP_Transmit_Buffer *GetTxBuffer()
    {
        struct SOMEIP_Transmit_Buffer *returnVal = nullptr;
        if (m_initComplete) {
            returnVal = m_tb;
        }
        return returnVal;
    }

    bool WaitForResponse(ReturnCode_t *result)
    {
        bool success = false;
        ReturnCode_t returnCode = RT_TIMEOUT;
        if (m_initComplete) {
            success = SOMEIP_CB_SemWait(&m_wait.semWaitForAck);
            if (success) {
                returnCode = (ReturnCode_t) m_wait.retCode;
            }
            SOMEIP_CB_SemDestroy(&m_wait.semWaitForAck);
        }
        if (result) {
            *result = returnCode;
        }
        return success;
    }

    void NoWait()
    {
        m_tb->ipV4Addr[0] = 0;
        m_tb->sendTime = 0;
        m_wait.semWaitForAck = nullptr;
    }

    uint8_t *GetRxBuffer()
    {
        return m_wait.rxBuf;
    }

    uint16_t GetRxLength()
    {
        return m_wait.rxLen;
    }

  protected:
    LAN866XClientImpl *m_client;
    SOMETR_t *m_transmit;
    ep_wait_vars m_wait = {};
    struct SOMEIP_Transmit_Buffer *m_tb = nullptr;
    bool m_fireAndForget;
    bool m_initComplete = false;
};

class LAN866XClientImpl : public LAN866XClient
{
  public:
    LAN866XClientImpl();

    /** Copy constructor */
    LAN866XClientImpl(LAN866XClientImpl *pCopy, uint16_t someIpInstaneId, uint8_t *ipAddr, uint8_t ipAddrLength, uint16_t port);

    static LAN866XClientImpl *GetByIpAdress(const uint8_t *ipAddr, uint8_t ipAddrLength);

    virtual bool IsNodeAvailable();

    virtual bool WasResetDetected();

    virtual void GetUserContext(void *&context);

    virtual void SetUserContext(void *context);

    virtual void AddListener(LAN866XClientListener *listener);

    virtual void RemoveListener(LAN866XClientListener *listener);

    virtual uint16_t GetSomeIpInstaneId();

    virtual void GetIpAddressAndPort(uint8_t **ipAddr, uint8_t *ipAddrLength, uint16_t *port);

    virtual ReturnCode_t Reboot(const RebootVar_t *dataIn);

    virtual ReturnCode_t Identify();

    virtual ReturnCode_t Lock(const LockVar_t *dataIn);

    virtual ReturnCode_t Shutdown();

    virtual ReturnCode_t GetStatus(GetStatusReply_t *dataOut);

    virtual ReturnCode_t GetCurrentWallclock(GetCurrentWallclockReply_t *dataOut);

    virtual ReturnCode_t ReadDiagnosisData(ReadDiagnosisDataReply_t *dataOut);

    virtual ReturnCode_t StartUpdate(const StartUpdateVar_t *dataIn);

    virtual ReturnCode_t WriteImage(const WriteImageVar_t *dataIn, WriteImageReply_t *dataOut);

    virtual ReturnCode_t FinishUpdate(const FinishUpdateVar_t *dataIn);

    virtual ReturnCode_t GetNetworkStatus(GetNetworkStatusReply_t *dataOut);

    virtual ReturnCode_t StartTDMeasurement(const StartTDMeasurementVar_t *dataIn);

    virtual ReturnCode_t GetTDMeasurementResult(const GetTDMeasurementResultVar_t *dataIn, GetTDMeasurementResultReply_t *dataOut);

    virtual ReturnCode_t StartPMATestMode(const StartPMATestModeVar_t *dataIn);

    virtual ReturnCode_t WakeupNetwork();

    virtual ReturnCode_t ConfigDigitalPin(const ConfigDigitalPinVar_t *dataIn);

    virtual ReturnCode_t ReleaseDigitalPins(const ReleaseDigitalPinsVar_t *dataIn);

    virtual ReturnCode_t OpenI2C(const OpenI2CVar_t *dataIn, OpenI2CReply_t *dataOut);

    virtual ReturnCode_t CloseI2C(const CloseI2CVar_t *dataIn);

    virtual ReturnCode_t ClearI2CBus(const ClearI2CBusVar_t *dataIn);

    virtual ReturnCode_t WriteI2C(const WriteI2CVar_t *dataIn);

    virtual ReturnCode_t WriteI2CFireAndForget(const WriteI2CVar_t *dataIn);

    virtual ReturnCode_t ReadI2C(const ReadI2CVar_t *dataIn, ReadI2CReply_t *dataOut);

    virtual ReturnCode_t WriteAndReadI2C(const WriteAndReadI2CVar_t *dataIn, ReadI2CReply_t *dataOut);

    virtual ReturnCode_t OpenGpio(const OpenGpioVar_t *dataIn, OpenGpioReply_t *dataOut);

    virtual ReturnCode_t OpenDebouncedGpio(const OpenDebouncedGpioVar_t *dataIn, OpenGpioReply_t *dataOut);

    virtual ReturnCode_t CloseGpio(const CloseGpioVar_t *dataIn);

    virtual ReturnCode_t EnableGpioPulseEvent(const EnableGpioPulseEventVar_t *dataIn);

    virtual ReturnCode_t EnableGpioCaptureEvent(const EnableGpioCaptureEventVar_t *dataIn);

    virtual ReturnCode_t DisableGpioEvent(const DisableGpioEventVar_t *dataIn);

    virtual ReturnCode_t SetGpio(const SetGpioVar_t *dataIn);

    virtual ReturnCode_t GetGpio(GetGpioReply_t *dataOut);

    virtual ReturnCode_t SetAndGetGpio(const SetGpioVar_t *dataIn, GetGpioReply_t *dataOut);

    virtual ReturnCode_t SetGpioFireAndForget(const SetGpioVar_t *dataIn);

    virtual ReturnCode_t GetGpioEvents(GetGpioEventsReply_t *dataOut);

    virtual ReturnCode_t OpenUart(const OpenUartVar_t *dataIn, OpenUartReply_t *dataOut);

    virtual ReturnCode_t CloseUart(const CloseUartVar_t *dataIn);

    virtual ReturnCode_t WriteUart(const WriteUartVar_t *dataIn);

    virtual ReturnCode_t WriteUartFireAndForget(const WriteUartFireAndForgetVar_t *dataIn);

    virtual ReturnCode_t ReadUart(const ReadUartVar_t *dataIn, ReadUartReply_t *dataOut);

    virtual ReturnCode_t OpenSpi(const OpenSpiVar_t *dataIn, OpenSpiReply_t *dataOut);

    virtual ReturnCode_t CloseSpi(const CloseSpiVar_t *dataIn);

    virtual ReturnCode_t WriteAndReadSpi(const WriteAndReadSpiVar_t *dataIn, WriteAndReadSpiReply_t *dataOut);

    virtual ReturnCode_t WriteSpiFireAndForget(const WriteSpiFireAndForgetVar_t *dataIn);

    virtual ReturnCode_t OpenAdc(const OpenAdcVar_t *dataIn, OpenAdcReply_t *dataOut);

    virtual ReturnCode_t CloseAdc(const CloseAdcVar_t *dataIn);

    virtual ReturnCode_t ReadAdc(const ReadAdcVar_t *dataIn, ReadAdcReply_t *dataOut);

    virtual ReturnCode_t OpenPwm(const OpenPwmVar_t *dataIn, OpenPwmReply_t *dataOut);

    virtual ReturnCode_t ClosePwm(const ClosePwmVar_t *dataIn);

    virtual ReturnCode_t WritePwm(const WritePwmVar_t *dataIn);

    virtual ReturnCode_t WritePwmFireAndForget(const WritePwmVar_t *dataIn);

    virtual ReturnCode_t WriteAndReadSpiExtended(const WriteAndReadSpiExtendedVar_t *dataIn, WriteAndReadSpiExtenedReply_t *dataOut);

    void DecodeResponse_OnTDMeasurementCompleted(const uint8_t *pRxBuf, uint16_t rxBufLen);

    void DecodeResponse_OnGpioEvents(const uint8_t *pRxBuf, uint16_t rxBufLen);

    void DecodeResponse_OnUartReceive(const uint8_t *pRxBuf, uint16_t rxBufLen);

    bool Init(bool subscribeToEvent);

    void CreateHeader(SOMEIP_Header &header, uint16_t methodId, enum SOMEIP_MsgType msgType, bool generateEvent, uint16_t *pSessionId);

    bool TransmitBuffer(SOMEIP_Transmit_Buffer *tb, uint16_t payloadLength, bool fireAndForget, ReturnCode_t &result, uint16_t sessionId);

    bool CheckAvailability(ReturnCode_t &result);

    vector<LAN866XClientListener *> m_listeners;
    std::mutex m_mutex;
    SOMETR_t *m_transmit = nullptr;
    uint8_t m_ipAddr[16] = {0};
    uint16_t m_serviceId = 0xFFFF;
    uint16_t m_someIpInstaneId = 0xFFFF;
    uint16_t m_sessionId = 1;
    uint16_t m_port = 0xFFFF;
    uint8_t m_ipAddrLength = 0xFF;
    bool m_resetDetected = true;
    bool m_available = true;
    void *m_userContext = nullptr;
};

typedef enum {
    Listener_NoEvent,
    Listener_NewDeviceFound,
    Listener_DeviceGone,
    Listener_DeviceBackOnline,
    Listener_DeviceReset,
    Listener_OnTDMeasurementCompleted,
    Listener_OnGpioEvents,
    Listener_OnUartReceive,
} ListenerEvent_t;

typedef struct
{
    ListenerEvent_t listenEvent;
    LAN866XFactoryListener *factoryListener;
    LAN866XClientListener *clientListener;
    LAN866XClient *lanClient;
    OnGpioEventsNotification_t OnGpioEventsVar;
    OnUartReceiveNotification_t OnUartReceiveVar;

} ListenerEntry_t;

template <typename T> class ThreadSafeFIFO
{
  public:
    ThreadSafeFIFO(size_t capacity) : capacity_(capacity)
    {
    }

    void push(const T &item)
    {
        std::unique_lock<std::mutex> lock(mutex_);
        cond_not_full_.wait(lock, [this]() { return queue_.size() < capacity_; });
        queue_.push(item);
        cond_not_empty_.notify_one();
    }

    std::optional<T> pop()
    {
        std::lock_guard<std::mutex> lock(mutex_);
        if (queue_.empty()) {
            return std::nullopt;
        }
        T item = queue_.front();
        queue_.pop();
        cond_not_full_.notify_one();
        return item;
    }

    bool empty() const
    {
        std::lock_guard<std::mutex> lock(mutex_);
        return queue_.empty();
    }

    bool full() const
    {
        std::lock_guard<std::mutex> lock(mutex_);
        return queue_.size() == capacity_;
    }

    void waitForData()
    {
        std::unique_lock<std::mutex> lock(mutex_);
        cond_not_empty_.wait(lock, [this]() { return !queue_.empty(); });
    }

  private:
    std::queue<T> queue_;
    size_t capacity_;
    mutable std::mutex mutex_;
    std::condition_variable cond_not_empty_;
    std::condition_variable cond_not_full_;
};

class LAN866XEventCaller
{
#define MAX_EVENTS 64
  public:
    static LAN866XEventCaller *GetInstance()
    {
        static LAN866XEventCaller *instance = nullptr;
        if (!instance) {
            instance = new LAN866XEventCaller();
            instance->Start();
        }
        return instance;
    }

    void setThreadPriorityToTimeCritical(std::thread &thread)
    {
#ifdef WIN32
        HANDLE threadHandle = reinterpret_cast<HANDLE>(thread.native_handle());
        SetThreadPriority(threadHandle, THREAD_PRIORITY_TIME_CRITICAL);
#else
        pthread_t threadHandle = thread.native_handle();
        struct sched_param param;
        param.sched_priority = sched_get_priority_max(SCHED_FIFO);
        pthread_setschedparam(threadHandle, SCHED_FIFO, &param);
#endif
    }

    void Start()
    {
        callbackThread = std::thread(&LAN866XEventCaller::CallbackAllListeners, this);
        setThreadPriorityToTimeCritical(callbackThread);
    }

    void Stop()
    {
        stopFlag = true;
        eventQueue.push(ListenerEntry_t()); // Push a dummy event to wake up the thread
        if (callbackThread.joinable()) {
            callbackThread.join();
        }
    }

    void CallbackAllListeners()
    {
        while (!stopFlag) {
            eventQueue.waitForData();
            bool called = false;
            do {
                called = false;
                auto entryOpt = eventQueue.pop();
                if (entryOpt) {
                    called = true;
                    ListenerEntry_t entry = *entryOpt;
                    switch (entry.listenEvent) {
                        case Listener_NewDeviceFound:
                            if (entry.factoryListener) {
                                entry.factoryListener->OnNewClientAvailable(entry.lanClient);
                            }
                            break;
                        case Listener_DeviceGone:
                            if (entry.clientListener) {
                                entry.clientListener->OnAvailable(entry.lanClient, false);
                            }
                            break;
                        case Listener_DeviceBackOnline:
                            if (entry.clientListener) {
                                entry.clientListener->OnAvailable(entry.lanClient, true);
                            }
                            break;
                        case Listener_DeviceReset:
                            if (entry.clientListener) {
                                entry.clientListener->OnAvailable(entry.lanClient, false);
                                entry.clientListener->OnAvailable(entry.lanClient, true);
                            }
                            break;
                        case Listener_OnTDMeasurementCompleted:
                            if (entry.clientListener) {
                                entry.clientListener->OnTDMeasurementCompleted();
                            }
                            break;
                        case Listener_OnGpioEvents:
                            if (entry.clientListener) {
                                entry.clientListener->OnGpioEvents(&entry.OnGpioEventsVar);
                            }
                            break;
                        case Listener_OnUartReceive:
                            if (entry.clientListener) {
                                entry.clientListener->OnUartReceive(&entry.OnUartReceiveVar);
                            }
                            break;
                        case Listener_NoEvent:
                            break;
                    }
                }
            } while (called);
        }
    }

    bool RaiseOnNewDeviceFound(LAN866XFactoryListener *listener, LAN866XClient *pNewClient)
    {
        ListenerEntry_t entry;
        entry.listenEvent = Listener_NewDeviceFound;
        entry.factoryListener = listener;
        entry.clientListener = nullptr;
        entry.lanClient = pNewClient;
        eventQueue.push(entry);
        return true;
    }

    bool RaiseOnDeviceAvailable(LAN866XClientListener *listener, LAN866XClient *pExistingClient, bool available)
    {
        ListenerEntry_t entry;
        entry.listenEvent = available ? Listener_DeviceBackOnline : Listener_DeviceGone;
        entry.factoryListener = nullptr;
        entry.clientListener = listener;
        entry.lanClient = pExistingClient;
        eventQueue.push(entry);
        return true;
    }

    bool RaiseOnDeviceReset(LAN866XClientListener *listener, LAN866XClient *pExistingClient)
    {
        ListenerEntry_t entry;
        entry.listenEvent = Listener_DeviceReset;
        entry.factoryListener = nullptr;
        entry.clientListener = listener;
        entry.lanClient = pExistingClient;
        eventQueue.push(entry);
        return true;
    }

    bool RaiseOnTDMeasurementCompleted(LAN866XClientListener *listener)
    {
        ListenerEntry_t entry;
        entry.listenEvent = Listener_OnTDMeasurementCompleted;
        entry.factoryListener = nullptr;
        entry.clientListener = listener;
        eventQueue.push(entry);
        return true;
    }

    bool RaiseOnGpioEvents(LAN866XClientListener *listener, OnGpioEventsNotification_t *data)
    {
        ListenerEntry_t entry;
        entry.listenEvent = Listener_OnGpioEvents;
        entry.factoryListener = nullptr;
        entry.clientListener = listener;
        memcpy(&entry.OnGpioEventsVar, data, sizeof(OnGpioEventsNotification_t));
        eventQueue.push(entry);
        return true;
    }

    bool RaiseOnUartReceive(LAN866XClientListener *listener, OnUartReceiveNotification_t *data)
    {
        ListenerEntry_t entry;
        entry.listenEvent = Listener_OnUartReceive;
        entry.factoryListener = nullptr;
        entry.clientListener = listener;
        memcpy(&entry.OnUartReceiveVar, data, sizeof(OnUartReceiveNotification_t));
        eventQueue.push(entry);
        return true;
    }

  protected:
    LAN866XEventCaller() : eventQueue(MAX_EVENTS), stopFlag(false)
    {
    }

  private:
    ThreadSafeFIFO<ListenerEntry_t> eventQueue;
    std::thread callbackThread;
    bool stopFlag;
};

} // namespace rcp
} // namespace microchip
